# todos.graphql
# query GetTodos {
#   todos {
#     id
#     text
#     done
#     user {
#       id
#       name
#     }
#   }
# }

 query GetItems {
   items {
     model
     details {
       ... on Console {
         analog_connections {
         
           port_kind
         }
       }
     }
   }
 }
