name: Trigger auto deployment for cloud

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '//**'
    - '.github/workflows/cloud-AutoDeployTrigger-b624a240-492e-4b7c-ae04-a51050610c85.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CLOUD_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CLOUD_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CLOUD_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: docker.io
          registryUsername: ${{ secrets.CLOUD_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CLOUD_REGISTRY_PASSWORD }}
          containerAppName: cloud
          resourceGroup: sonic-sync
          imageToBuild: maboah/cloud:${{ github.sha }}
          dockerfilePath: Dockerfile


